on: push
jobs:
  license_check_pip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Get explicit and transitive dependencies
      run: |
        pip install -r prod_requirements.txt
        pip freeze > requirements-all.txt
    - name: Check python
      id: license_check_report
      uses: pilosus/action-pip-license-checker@v0.5.0
      with:
        requirements: 'requirements-all.txt'
        fail: 'Copyleft,Error,Other'
        exclude: 'pylint.*'
    - name: Print report
      if: ${{ always() }}
      run: echo "${{ steps.license_check_report.outputs.report }}"
  license_check_npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: omap/frontend/static_src
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" >> ~/.npmrc
      - name: Run npm install
        run: npm install
      - name: Test env
        run: echo $GITHUB_WORKSPACE
      - name: Check licenses
        uses: tangro/actions-license-check@v1.0.7
        with:
          allowed-licenses: 'MIT; ISC; Apache-2.0; BSD'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}